### PR TITLE
Fix Pants native client handling.

### LINKED ISSUE #182: Scie pants fails out of the box for Pants releases that include the native client.
Looks like so:
```
$ PANTS_VERSION=2.17.0a1 pants -V
Bootstrapping Pants 2.17.0a1 using cpython 3.9.15
Installing pantsbuild.pants==2.17.0a1 into a virtual environment at /home/jsirois/.cache/nce/1239dc7f2c4e6bb57836aa10d4b93b4a7bd7016bedcb8ca326ef6b803855e362/bindings/venvs/2.17.0a1
New virtual environment successfully created at /home/jsirois/.cache/nce/1239dc7f2c4e6bb57836aa10d4b93b4a7bd7016bedcb8ca326ef6b803855e362/bindings/venvs/2.17.0a1.
Error: Failed to exec "/home/jsirois/.cache/nce/1239dc7f2c4e6bb57836aa10d4b93b4a7bd7016bedcb8ca326ef6b803855e362/bindings/venvs/2.17.0a1/lib/python3.9/site-packages/pants/bin/native_client" with argv ["/home/jsirois/.cache/nce/1239dc7f2c4e6bb57836aa10d4b93b4a7bd7016bedcb8ca326ef6b803855e362/bindings/venvs/2.17.0a1/lib/python3.9/site-packages/pants/bin/native_client", "--python-repos-find-links=-[\'file:///home/jsirois/.cache/nce/1239dc7f2c4e6bb57836aa10d4b93b4a7bd7016bedcb8ca326ef6b803855e362/bindings/find_links/2.17.0a1/a577739f/index.html\']", "-V"]: EACCES: Permission denied
```

The issue is:
```
$ ls -l /home/jsirois/.cache/nce/1239dc7f2c4e6bb57836aa10d4b93b4a7bd7016bedcb8ca326ef6b803855e362/bindings/venvs/2.17.0a1/lib/python3.9/site-packages/pants/bin/
total 24064
-rw-r--r-- 1 jsirois jsirois     7305 May 21 16:59 daemon_pants_runner.py
-rw-r--r-- 1 jsirois jsirois        0 May 21 16:59 __init__.py
-rw-r--r-- 1 jsirois jsirois    12021 May 21 16:59 local_pants_runner.py
-rw-r--r-- 1 jsirois jsirois 24584416 May 21 16:59 native_client
-rw-r--r-- 1 jsirois jsirois      289 May 21 16:59 pants_env_vars.py
-rw-r--r-- 1 jsirois jsirois     4309 May 21 16:59 pants_loader.py
-rw-r--r-- 1 jsirois jsirois     5226 May 21 16:59 pants_runner.py
drwxr-xr-x 2 jsirois jsirois     4096 May 21 16:59 __pycache__
-rw-r--r-- 1 jsirois jsirois     6471 May 21 16:59 remote_pants_runner.py
```

It looks like `scie-pants` should be defensive against wheel perms here and ~`chmod +x`:
https://github.com/pantsbuild/scie-pants/blob/750ccd78dc5e55ad7209accb9e5b5b044e2d7326/tools/src/scie_pants/install_pants.py#L121-L127

### PR DESCRIPTION
**Pull request by jsirois**
Guard against the Pants wheel not containing an executable native
client / Pip not installing the native client with executable
permissions.

Today this guards the former:
```
$ zipinfo ~/Downloads/pantsbuild.pants-2.17.0a1-cp39-cp39-manylinux2014_x86_64.whl | grep native_client
-rw-r--r--  2.0 unx 24584416 b- defN 23-May-19 23:21 pants/bin/native_client
```

Fixes #182

### CODE REVIEW

File: package/src/test.rs [hunk 1]
```diff
@@ -822,3 +823,23 @@ export PANTS_CONFIG_FILES=${{PANTS_TOML}}
         String::from_utf8(output.stdout.to_vec()).unwrap().trim()
     );
 }
+
+fn test_pants_native_client_perms_issue_182(scie_pants_scie: &Path) {
```
Comment (jsirois) [inline package/src/test.rs:827]: Prior to the fix this fails like so:
```
$ cargo run -p package -- test --tools-pex-mismatch-warn
...
>> Verifying scie-pants sets executable perms on the Pants native client binary when present (https://github.com/pantsbuild/scie-pants/issues/182)
Bootstrapping Pants 2.17.0a1 using cpython 3.9.15
Installing pantsbuild.pants==2.17.0a1 into a virtual environment at /home/jsirois/.cache/nce/7ab402e954e513cf9cca8ba4d401574fdb99e06731f47c1047f4acb7d66dd3ec/bindings/venvs/2.17.0a1
New virtual environment successfully created at /home/jsirois/.cache/nce/7ab402e954e513cf9cca8ba4d401574fdb99e06731f47c1047f4acb7d66dd3ec/bindings/venvs/2.17.0a1.
Error: Failed to exec "/home/jsirois/.cache/nce/7ab402e954e513cf9cca8ba4d401574fdb99e06731f47c1047f4acb7d66dd3ec/bindings/venvs/2.17.0a1/lib/python3.9/site-packages/pants/bin/native_client" with argv ["/home/jsirois/.cache/nce/7ab402e954e513cf9cca8ba4d401574fdb99e06731f47c1047f4acb7d66dd3ec/bindings/venvs/2.17.0a1/lib/python3.9/site-packages/pants/bin/native_client", "--python-repos-find-links=-[\'file:///home/jsirois/.cache/nce/7ab402e954e513cf9cca8ba4d401574fdb99e06731f47c1047f4acb7d66dd3ec/bindings/find_links/2.17.0a1/a577739f/index.html\']", "-V"]: EACCES: Permission denied
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Command PANTS_VERSION="2.17.0a1" "/home/jsirois/dev/pantsbuild/jsirois-scie-pants/target/debug/build/package-94b0632f4934a259/out/dist/scie-pants/scie-pants-linux-x86_64" "-V" failed with exit code: Some(1)
STDOUT not captured.
STDERR not captured.', package/src/test.rs:841:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

After the fix the test passes and:
```
$ ls -l /home/jsirois/.cache/nce/62e79b97d31de243ec0ee9e8074771dce13bbe858b5c0540868bd17decbc8623/bindings/venvs/2.17.0a1/lib/python3.9/site-packages/pants/bin/
total 24064
-rw-r--r-- 1 jsirois jsirois     7305 May 21 17:35 daemon_pants_runner.py
-rw-r--r-- 1 jsirois jsirois        0 May 21 17:35 __init__.py
-rw-r--r-- 1 jsirois jsirois    12021 May 21 17:35 local_pants_runner.py
-rwxr-xr-x 1 jsirois jsirois 24584416 May 21 17:35 native_client
-rw-r--r-- 1 jsirois jsirois      289 May 21 17:35 pants_env_vars.py
-rw-r--r-- 1 jsirois jsirois     4309 May 21 17:35 pants_loader.py
-rw-r--r-- 1 jsirois jsirois     5226 May 21 17:35 pants_runner.py
drwxr-xr-x 2 jsirois jsirois     4096 May 21 17:35 __pycache__
-rw-r--r-- 1 jsirois jsirois     6471 May 21 17:35 remote_pants_runner.py
```

**Review by stuhood — APPROVED** [review]
Thank you! Not sure why my previous test didn't encounter this.

**Review by benjyw — APPROVED** [review]
