### PR TITLE
Fix support for Pants 2.25.x / Python 3.11 

### LINKED ISSUE #424: Unable to run pants 2.25.0.dev0 due to "No interpreter compatible with the requested constraints was found:" error
**Describe the bug**

Running pants 2.25.0.dev0 upgrades the version of Python used, but this doesn't seem to have worked completely, actually attempting to run Pants gives an error like:

```
Failed to find compatible interpreter on path /Users/huon/Library/Caches/nce/7af7058f7c268b4d87ed7e08c2c7844ef8460863b3e679db3afdce8bb1eedfae/cpython-3.11.9+20240415-aarch64-apple-darwin-install_only.tar.gz/python/bin/python3.11.

Examined the following interpreters:
1.) /Users/huon/Library/Caches/nce/7af7058f7c268b4d87ed7e08c2c7844ef8460863b3e679db3afdce8bb1eedfae/cpython-3.11.9+20240415-aarch64-apple-darwin-install_only.tar.gz/python/bin/python3.11 CPython==3.11.9

No interpreter compatible with the requested constraints was found:

  Version matches CPython<3.10,>=3.8
Error: Failed to establish atomic directory /Users/huon/Library/Caches/nce/6faa4322d1df41d032e4938795c6f2c262ab92bb642a9bac1101cb7d1631f9c1/locks/install-b4ff91a6f4dedb37b388e53c0e15b581f82e68706a77a04f1d9940d3e97e0da1. Population of work directory failed: Boot binding command failed: exit status: 1

Isolates your Pants from the elements.

Please select from the following boot commands:

<default> (when SCIE_BOOT is not set in the environment)  Detects the current Pants installation and launches it.
bootstrap-tools                                           Introspection tools for the Pants bootstrap process.
update                                                    Update scie-pants.

You can select a boot command by setting the SCIE_BOOT environment variable.
```

(Filed here not scie-pants because I'm guessing this might be some metadata in the Pants wheel? It seems like the interpreter is configured correctly.)

Reproducer: run `PANTS_VERSION=2.25.0.dev0 pants version`
                                                                                                                                              
**Pants version**
2.25.0.dev0

**OS**

macOS, Linux

**Additional info**
N/A

### PR DESCRIPTION
**Pull request by huonw**
Fixes #424 

This makes a few adjustments to support running Pants 2.25.0.dev0 and newer, which run using Python 3.11 (https://github.com/pantsbuild/pants/pull/21528), iterating on #351. Particularly:

- expanding tools.pex's interpreter constraints to include 3.11 (and also 3.10, which seems fine)
- add a test (NB. Pants 2.25 cannot run on macOS older than 13 / 14, depending on platform, so this test is conditional: https://github.com/pantsbuild/pants/pull/21655)
- hardcoding that 2.25.0.dev0 uses Python 3.11, to use the optimised "hit the exact URL first time" codepath, instead of having to try all Python versions: https://github.com/pantsbuild/scie-pants/blob/d50bd33fd67e944384c9548811a66c1cb03113a5/tools/src/scie_pants/pants_version.py#L239-L252

This thus preps scie-pants release 0.12.1 too, which I'll tag once merged.

### CODE REVIEW

File: package/src/test.rs [hunk 1]
```diff
@@ -334,6 +372,31 @@ fn test_pants_bootstrap_tools(scie_pants_scie: &Path) {
     .unwrap();
 }
 
+fn test_pants_2_25_using_python_3_11(scie_pants_scie: &Path) {
+    integration_test!("Verifying we can run Pants 2.25+, which uses Python 3.11");
+    if is_macos_thats_too_old(13, 14) {
+        log!(
+            Color::Yellow,
+            "Pants 2.25 cannot run on this version of macOS => skipping"
+        );
```
Comment (kaos) [inline package/src/test.rs:381]: It would be nice, if not in the message, but at least as a code comment, the reason we can't run pants 2.25 on these older versions of MacOS.

**Review by kaos — APPROVED** [review]

**Comment by cburroughs** [comment]
Thanks for fixing this up.  I was able to build this and run not just `version` but `fmt`, `test`, etc.

**Review by cburroughs — APPROVED** [review]
